name: deploy
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Optionally, add build steps here if your site needs to be processed
      
      # Create .nojekyll file to bypass Jekyll processing
      - name: Create .nojekyll file
        run: touch .nojekyll
        
      # Create a .gitignore file for GitHub Pages deployment
      - name: Create .gitignore for deployment
        run: |
          echo "package.json" > .gitignore
          echo "package-lock.json" >> .gitignore
          echo "export_to_latex.js" >> .gitignore
          echo "push.sh" >> .gitignore
          echo "setup.sh" >> .gitignore
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: 'package.json,package-lock.json,export_to_latex.js'